services:
  rainfrog-db:
    container_name: rainfrog-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "rainfrog"
    ports:
      - "${PORT}:5432"
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
